export const actionTypes = {
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_ERROR: 'FETCH_PRODUCTS_ERROR',

  FETCH_SINGLE_PRODUCT_SUCCESS: 'FETCH_SINGLE_PRODUCT_SUCCESS',
  FETCH_SINGLE_PRODUCT_ERROR: 'FETCH_SINGLE_PRODUCT_ERROR',

  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
};
