export const actionTypes = {
  // products
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_ERROR: 'FETCH_PRODUCTS_ERROR',

  FETCH_SINGLE_PRODUCT_SUCCESS: 'FETCH_SINGLE_PRODUCT_SUCCESS',
  FETCH_SINGLE_PRODUCT_ERROR: 'FETCH_SINGLE_PRODUCT_ERROR',

  REMOVE_PRODUCT: 'REMOVE_PRODUCT',

  // search npm packanges
  FETCH_SEARCH_SUCCESS: 'FETCH_SEARCH_SUCCESS',
  FETCH_SEARCH_ERROR: 'FETCH_SEARCH_ERROR',

  DELETE_PREV_SEARCH_RESULT: 'DELETE_PREV_SEARCH_RESULT',
  WAIT_FOR_DATA_FETCHING: 'WAIT_FOR_DATA_FETCHING',
};
